name: Scratch
options:
  bundleIdPrefix: com.scratch
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "26.0"
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture.git
    version: 1.23.1
  TCACoordinators:
    url: https://github.com/johnpatrickmorgan/TCACoordinators.git
    version: 0.13.0
targets:
  ScratchApp:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: application
    platform: iOS
    sources: [Sources]
    dependencies:
      - package: ComposableArchitecture
      - package: TCACoordinators
    info:
      path: Sources/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: YES
    postCompileScripts:
      - path: swiftformat.sh
        name: SwiftFormat
      - path: swiftlint.sh
        name: SwiftLint
  ScratchTests:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]
    dependencies:
      - target: ScratchApp
    info:
      path: Tests/Info.plist
    postCompileScripts:
      - path: swiftformat.sh
        name: SwiftFormat
      - path: swiftlint.sh
        name: SwiftLint
