name: BarBeeQ
options:
  bundleIdPrefix: com.barbeeq
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "26.0"
packages:
  RPMacro:
    url: https://github.com/RomanPodymov/RPMacro.git
    branch: feature/macros
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture.git
    version: 1.22.3
  TCACoordinators:
    url: https://github.com/johnpatrickmorgan/TCACoordinators.git
    version: 0.13.0
  CombineFirebaseFirestore:
    url: https://github.com/RomanPodymov/CombineFirebase.git
    branch: master
  CombineFirebaseAuth:
    url: https://github.com/RomanPodymov/CombineFirebase.git
    branch: master
targets:
  BarBeeQApp:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: application
    platform: iOS
    sources: [Sources]
    dependencies:
      - package: ComposableArchitecture
      - package: TCACoordinators
      - package: CombineFirebaseFirestore
      - package: CombineFirebaseAuth
      - package: RPMacro
    info:
      path: Sources/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: YES
    postCompileScripts:
      - path: swiftformat.sh
        name: SwiftFormat
      - path: swiftlint.sh
        name: SwiftLint
  BarBeeQAppTests:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]
    dependencies:
      - target: BarBeeQApp
    info:
      path: Tests/Info.plist
    postCompileScripts:
      - script: "mint run swiftformat . --swiftversion 5.9"
        name: SwiftFormat
      - script: "mint run swiftlint"
        name: SwiftLint
